friends/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('person/', include('person.urls')),
]

person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [
    path('api/', views.PersonList.as_view()),
    path('', views.IndexView.as_view(), name='index'),
    path('load_data/', views.load_data, name='load_data'),
    path('<pk>/', views.DetailView.as_view(), name='detail'),
]

person/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    age = models.PositiveIntegerField(null=True)
    gender = models.CharField(max_length=6, choices=[('male', 'male'), ('female', 'female')], null=True)
    friends = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return str(self.first_name) + ' ' + str(self.last_name) + ', id: ' + str(self.id)

person/views.py
from django.views import generic
from django.shortcuts import redirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Person
from .serializers import PersonSerializer
import os


def load_data(request):
    module_dir = os.path.dirname(__file__)
    file_path = os.path.join(module_dir, 'static/person/data.txt')
    with open(file_path) as f:
        lines = [x.strip().split(';') for x in f.readlines()]
        f.close()

    persons = {}
    p_objects = []

    for line in lines:
        id = int(line[0])
        persons[id] = { 'firstname' : line[1],
                        'lastname'  : line[2],
                        'age'       : int(line[3] if line[3] else 0),
                        'sex'       : line[4],
                        'friends'   : [int(x) for x in line[5].split(',')]}

        p = Person(id, line[1], line[2], int(line[3] if line[3] else 0), line[4])
        p_objects.append(p)
        p.save()

    for p in p_objects:
        [p.friends.add(x) for x in p_objects if x.id in persons[p.id]['friends']]
        p.save()

    return redirect('person:index')


class PersonList(APIView):

    def get(self, request):
        persons = Person.objects.all()
        serializer = PersonSerializer(persons, many=True)
        return Response(serializer.data)

    def post(self,request):
        serializer = PersonSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class IndexView(generic.ListView):
    template_name = 'person/index.html'
    context_object_name = 'persons'

    def get_queryset(self):
        return Person.objects.all()


class DetailView(generic.DetailView):
    model = Person
    template_name = 'person/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)

        selected_person = self.get_object()

        friend_ids = selected_person.friends.values_list('id', flat=True)

        pf = Person.objects.prefetch_related('friends')
        fofs = [list(x.friends.all()) for x in pf if x.id in friend_ids] # friends of friends
        fofs_flat = [item for sublist in fofs for item in sublist if item.id != selected_person.id and item.id not in friend_ids]
        fofs_flat = list(set(fofs_flat))

        context['fofs'] = fofs_flat

        sf = []
        for friend in fofs_flat:
            counter = 0
            for fof in fofs:
                if friend in fof:
                    counter += 1
                    if counter == 2:
                        sf.append(friend)
                        break

        context['sf'] = sf

        return context

person/templates/person/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Friendsbook</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'person/style.css' %}"/>
    <script src="{% static 'person/script.js' %}"></script>
</head>
<body onload="load()">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'person:index' %}">Friendsbook</a>
          </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

person/templates/person/detail.html
{% extends 'person/base.html' %}
{% block body %}
    <h1>{{ object.first_name }} {{ object.last_name }}</h1>
    <!-- direct friends -->
    <h3>friends</h3>
    <ul>
    {% for friend in object.friends.all %}
        <li>{{ friend.first_name }} {{ friend.last_name }}</li>
    {% endfor %}
    </ul>
    <!-- friends of friends -->
    <h3>friends of friends</h3>
    <ul>
        {% for f in fofs %}
            <li>{{ f.first_name }} {{ f.last_name }}</li>
        {% endfor %}
    </ul>
    <!-- suggested friends -->
    <h3>suggested friends</h3>
    <ul>
        {% for f in sf %}
            <li>{{ f.first_name }} {{ f.last_name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

person/templates/person/index.html
{% extends 'person/base.html' %}
{% block body %}

<select id="persons_drop">
    <option value="-1">Select person</option>
    {% for person in persons %}
        <option value="{{ person.id }}">{{ person.first_name }} {{ person.last_name }}</option>
    {% endfor %}
</select>
<button onclick="showDetails();">Show</button>

<form action="{% url 'person:load_data' %}"> 
    <input type="submit" value="Load data" />
</form>
{% endblock %}